apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipecheck.fullname" . }}
  labels:
    {{- include "pipecheck.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.checks | nindent 4 }}